[#11] Create project skeleton
Sheptytskyid/JavaCoreFinalProjectGroup6 pull request #12
Opened 2017-01-24 22:02 UTC by KoliushkoArtem

2017-01-25 22:46 UTC, zozich requested changes

2017-01-25 22:46 UTC, zozich commented on src/main/java/controller/Controller.java
> +    ArrayList<Hotel> hotelArrayList = new ArrayList();
??? why

2017-01-25 22:46 UTC, zozich commented on src/main/java/controller/Controller.java
> +    public T save(T obj) {
Why are there DAO methods in controller?

2017-01-25 22:46 UTC, zozich commented on src/main/java/controller/Controller.java
> +public class Controller<T> {
1. Why is this controller parameterized
2. You need one controller. Call it more specific, e.g., HotelController

2017-01-25 22:46 UTC, zozich commented on src/main/java/controller/Controller.java
> +    public ArrayList<Hotel> getHotelsByName(String hotelName) {
Use interfaces everywhere, not concrete implementations

2017-01-25 22:46 UTC, zozich commented on src/main/java/dao/AbstractDAO.java
> +    ArrayList<Hotel> hotelArrayList = new ArrayList();
Why list of hotels in abstract DAO?

2017-01-25 22:46 UTC, zozich commented on src/main/java/dao/HotelDAOImpl.java
> +public class HotelDAOImpl extends AbstractDAO{
Abstract DAO is parameterized

2017-01-25 22:46 UTC, zozich commented on src/main/java/Main.java
Create base package com.manardenza for all code

2017-01-25 22:46 UTC, zozich commented on src/main/java/dao/AbstractDAO.java
> +    public T save(T obj) {
Remove all generic methods for now. Later create only ones you need.

2017-01-25 22:46 UTC, zozich commented on src/main/java/controller/Controller.java
> +
Inject service here (preferably via constructor)

2017-01-25 22:46 UTC, zozich commented on src/main/java/entities/Hotel.java
> +package entities;
Call package `entity`

2017-01-25 22:46 UTC, zozich commented on src/main/java/entities/Hotel.java
> +public class Hotel {
Create class AbstractObject - parent for all entity classes. It will contain `id` field

2017-01-25 22:46 UTC, zozich commented on src/main/java/login/CurrentUser.java
> +public class CurrentUser {
Make this class and all service classes singletons

2017-01-25 22:46 UTC, zozich commented on src/main/java/servise/Service.java
> +public class Service {
1. Call this class more specific - the same as controller.
2. Inject DAO classes

2017-01-25 23:16 UTC, zozich requested changes

2017-01-25 23:16 UTC, zozich commented on src/main/java/dao/AbstractDao.java
> +    ArrayList<Hotel> hotelArrayList = new ArrayList();
Why list of hotels in abstract DAO?

2017-01-25 23:16 UTC, zozich commented on src/main/java/dao/HotelDaoImpl.java
> +public class HotelDaoImpl extends AbstractDao {
AbstractDao is parameterized

2017-01-26 15:24 UTC, Sheptytskyid commented on src/main/java/manardenza/com/controller/HotelController.java
> +    public HotelController() {
Make this private, according to the singleton pattern

2017-01-26 15:24 UTC, Sheptytskyid commented on src/main/java/manardenza/com/controller/HotelController.java
> +    public Room bookRoom(long roomId, long userId, long hotelId) {
Perhaps we should add dates for booking as well

2017-01-26 15:24 UTC, Sheptytskyid commented on src/main/java/manardenza/com/controller/HotelController.java
> +    public boolean cancelReservation(long roomId, long userId, long hotelId) {
We should add dates

2017-01-26 15:24 UTC, Sheptytskyid commented on src/main/java/manardenza/com/dao/AbstractDao.java
> +
Add private empty constructor to block creation of multiple objects of this class

2017-01-26 15:24 UTC, Sheptytskyid commented on src/main/java/manardenza/com/dao/HotelDaoImpl.java
> +public class HotelDaoImpl<T> extends AbstractDao {
HotelDaoImpl extends AbstractDao<Hotel>

2017-01-26 15:24 UTC, Sheptytskyid commented on src/main/java/manardenza/com/dao/HotelDaoImpl.java
> +public class HotelDaoImpl<T> extends AbstractDao {
HotelDaoImpl extends AbstractDao<Hotel>

2017-01-26 15:24 UTC, Sheptytskyid commented on src/main/java/manardenza/com/dao/HotelDaoImpl.java
> +    }
Override getAll()

2017-01-26 15:24 UTC, Sheptytskyid commented on src/main/java/manardenza/com/dao/UserDaoImpl.java
> +    }
Same comments as in HotelDaoImpl

2017-01-26 15:24 UTC, Sheptytskyid commented on src/main/java/manardenza/com/dao/HotelDaoImpl.java
> +}
Add list of Hotels

2017-01-26 15:24 UTC, Sheptytskyid commented on src/main/java/manardenza/com/login/CurrentUser.java
> +    }
Add private empty constructor to avoid multiple objects creation

2017-01-26 15:24 UTC, Sheptytskyid commented on src/main/java/manardenza/com/console/ConsoleMain.java
> +package manardenza.com.console;
According to Andrew's comment this should have been "com.manardenza"

2017-01-26 16:26 UTC, AbseliamovEnver approved these changes

2017-01-26 16:51 UTC, zozich requested changes

2017-01-26 16:51 UTC, zozich commented on src/main/java/com/manardenza/console/ConsoleMain.java
> +public class ConsoleMain {
All singleton classes should have private constructor

2017-01-26 16:51 UTC, zozich commented on src/main/java/com/manardenza/controller/HotelController.java
> +        hotelService = HotelService.getInstance();
use "this." for accessing instance variables

2017-01-26 16:51 UTC, zozich commented on src/main/java/com/manardenza/controller/HotelController.java
> +    public void userRegistration(User userToRegistration) {
1. better to call methods as actions, e.g., registerUser
2. Consider moving this and all user related methods to UserController + UserService

2017-01-26 16:51 UTC, zozich commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +    public boolean deleteAll(List<T> obj) {
Not needed I guess

2017-01-26 16:51 UTC, zozich commented on src/main/java/com/manardenza/dao/HotelDaoImpl.java
> +    List<Hotel> hotelList = new ArrayList<>();
List<T> may be stored inside abstract dao. Make it protected, so all children will have access to it

2017-01-26 16:51 UTC, zozich commented on src/main/java/com/manardenza/entity/Hotel.java
> +    private ArrayList<Room> rooms;
Use interface

2017-01-26 16:51 UTC, zozich commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +public abstract class AbstractDao<T> {
Make T extend AbstractObject

2017-01-26 16:51 UTC, zozich commented on src/main/java/com/manardenza/entity/Reservation.java
> +    private LocalDate reservedFrom;
Use java.util.Date

2017-01-26 16:51 UTC, zozich commented on src/main/java/com/manardenza/entity/Reservation.java
> +public class Reservation extends AbstractObject {
Reservation does not need to have id

2017-01-26 17:06 UTC, zozich approved these changes

2017-01-26 18:25 UTC, merged