#12Logback_xml
Sheptytskyid/JavaCoreFinalProjectGroup6 pull request #17
Opened 2017-01-26 00:34 UTC by AbseliamovEnver

Update logback.xml

2017-01-28 13:17 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-28 13:17 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <appender name="FILE-ERROR" class="ch.qos.logback.core.rolling.RollingFileAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-28 13:17 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <root level="INFO">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-28 13:17 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <appender name="FILE-AUDIT" class="ch.qos.logback.core.rolling.RollingFileAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-28 13:17 UTC, Sheptytskyid commented
SonarQube analysis reported 4 issues
* ![MINOR][MINOR] 4 minor

Watch the comments in this conversation to review them.

[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-01-28 13:25 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <appender name="FILE-ERROR" class="ch.qos.logback.core.rolling.RollingFileAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-28 13:25 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <root level="INFO">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-28 13:25 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-28 13:25 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <appender name="FILE-AUDIT" class="ch.qos.logback.core.rolling.RollingFileAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-29 16:29 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <appender name="FILE-ERROR" class="ch.qos.logback.core.rolling.RollingFileAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-29 16:29 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-29 16:29 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <root level="INFO">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-29 16:29 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <appender name="FILE-AUDIT" class="ch.qos.logback.core.rolling.RollingFileAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-29 16:40 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <appender name="FILE-ERROR" class="ch.qos.logback.core.rolling.RollingFileAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-29 16:40 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <root level="INFO">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-29 16:40 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-29 16:40 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <appender name="FILE-AUDIT" class="ch.qos.logback.core.rolling.RollingFileAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-29 16:54 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +            <appender name="FILE-ERROR" class="ch.qos.logback.core.rolling.RollingFileAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-29 16:54 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +            <root level="INFO">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-29 16:54 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +            <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-29 16:54 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +            <appender name="FILE-AUDIT" class="ch.qos.logback.core.rolling.RollingFileAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-29 17:04 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +   <appender name="FILE-ERROR" class="ch.qos.logback.core.rolling.RollingFileAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-29 17:04 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +   <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-29 17:04 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +   <appender name="FILE-AUDIT" class="ch.qos.logback.core.rolling.RollingFileAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-29 17:04 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +   <root level="INFO">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-29 19:40 UTC, zozich requested changes
Please amend

2017-01-29 19:40 UTC, zozich commented on pom.xml
> +            <groupId>org.slf4j</groupId>
Do you really need Slf4j here for Logback to work?

2017-01-29 19:40 UTC, zozich commented on src/main/resources/logback.xml
> +   <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
You have indentation of 3 in this file. Make it 4

2017-01-29 19:40 UTC, zozich commented on src/main/resources/logback.xml
> +                <maxHistory>30</maxHistory>
Remove all configs that are not directly required by the specification

2017-01-29 19:40 UTC, zozich commented on src/main/resources/logback.xml
> +        <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
Do you really need several rolling policies here?

2017-01-29 19:40 UTC, zozich commented on src/main/resources/logback.xml
> +            <onMatch>ACCEPT</onMatch>
Is it really needed? Isn't just level enough?

2017-01-30 17:15 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <root level="INFO">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-30 17:15 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <appender name="FILE-ERROR" class="ch.qos.logback.core.rolling.RollingFileAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-30 17:15 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <statusListener class="ch.qos.logback.core.status.NopStatusListener"/>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-30 17:15 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-30 17:15 UTC, Sheptytskyid commented on src/main/resources/logback.xml
> +    <appender name="FILE-AUDIT" class="ch.qos.logback.core.rolling.RollingFileAppender">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=xml%3AIndentCheck)

2017-01-30 17:15 UTC, Sheptytskyid commented
SonarQube analysis reported 5 issues
* ![MINOR][MINOR] 5 minor

Watch the comments in this conversation to review them.

[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-01-30 17:22 UTC, zozich approved these changes
Cool!

2017-01-30 17:51 UTC, merged