[#27] Implement DB serialization
Sheptytskyid/JavaCoreFinalProjectGroup6 pull request #22
Opened 2017-01-29 16:34 UTC by Sheptytskyid

2017-01-29 16:37 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/HotelDaoImpl.java
> +    {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Move the contents of this initializer to a standard constructor or to field initializers. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1171)

2017-01-29 16:37 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            e.printStackTrace();
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Use a logger to log this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1148)

2017-01-29 16:37 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +        } catch (ClassNotFoundException e) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Either log or rethrow this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1166)
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Combine this catch with the one at line 31, which has the same body. (sonar.java.source not set. Assuming 7 or greater.) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS2147)

2017-01-29 16:37 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            e.printStackTrace();
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Use a logger to log this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1148)

2017-01-29 16:37 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            oos.writeObject(database);
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Make the "java.util.List" class "Serializable" or don't write it. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS2118)

2017-01-29 16:37 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +        } catch (IOException e) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Either log or rethrow this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1166)

2017-01-29 16:37 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            e.printStackTrace();
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Use a logger to log this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1148)

2017-01-29 16:37 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +        } catch (IOException e) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Either log or rethrow this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1166)

2017-01-29 16:37 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/UserDaoImpl.java
> +    {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Move the contents of this initializer to a standard constructor or to field initializers. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1171)

2017-01-29 16:37 UTC, Sheptytskyid commented
SonarQube analysis reported 10 issues
* ![MAJOR][MAJOR] 6 major
* ![MINOR][MINOR] 4 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-01-29 16:47 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +    public void saveToFile() {
Make this private

2017-01-29 16:48 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +    public void readFromFile() {
Make this private

2017-01-29 19:39 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            e.printStackTrace();
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Use a logger to log this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1148)

2017-01-29 19:39 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            oos.writeObject(database);
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Make the "java.util.List" class "Serializable" or don't write it. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS2118)

2017-01-29 19:39 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +        } catch (IOException e) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Either log or rethrow this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1166)

2017-01-29 19:39 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            e.printStackTrace();
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Use a logger to log this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1148)

2017-01-29 19:39 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +        } catch (IOException | ClassNotFoundException e) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Either log or rethrow this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1166)

2017-01-29 19:39 UTC, Sheptytskyid commented
SonarQube analysis reported 5 issues
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 2 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-01-29 20:09 UTC, zozich commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            e.printStackTrace();
You will need to do this - log this exception with the logger. As logging branch is not merged yet, use //FIXME: comments not to forget to fix this issue in future

2017-01-29 20:09 UTC, zozich commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +        } catch (IOException e) {
//FIXME:

2017-01-29 20:09 UTC, zozich commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            e.printStackTrace();
//FIXME:

2017-01-29 20:09 UTC, zozich commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +        } catch (IOException | ClassNotFoundException e) {
//FIXME:

2017-01-29 20:31 UTC, zozich requested changes
Please amend

2017-01-29 20:31 UTC, zozich commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(databaseFile))) {
Try storing ObjectOutputStream variable as an instance variable not to open new stream each time any database call is performed

2017-01-29 21:09 UTC, zozich requested changes
Amend

2017-01-29 21:09 UTC, zozich commented on src/main/java/com/manardenza/entity/Hotel.java
> +public class Hotel extends AbstractObject implements Serializable {
If you have marked AbstractObject as Serializable, this class will become so as well

2017-01-29 21:09 UTC, zozich commented on src/main/java/com/manardenza/entity/Reservation.java
> +public class Reservation implements Serializable {
If you have marked AbstractObject as Serializable, this class will become so as well

2017-01-29 21:09 UTC, zozich commented on src/main/java/com/manardenza/entity/Room.java
> +public class Room extends AbstractObject implements Serializable{
If you have marked AbstractObject as Serializable, this class will become so as well

2017-01-29 21:09 UTC, zozich commented on src/main/java/com/manardenza/entity/User.java
> +public class User extends AbstractObject implements Serializable {
If you have marked AbstractObject as Serializable, this class will become so as well

2017-01-30 13:30 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +        } catch (IOException | ClassNotFoundException ex) { //FIXME: Either log or rethrow this exception.
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Take the required action to fix the issue indicated by this comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1134)
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Either log or rethrow this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1166)

2017-01-30 13:30 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            ex.printStackTrace(); //FIXME: Use a logger to log this exception.
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Take the required action to fix the issue indicated by this comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1134)
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Use a logger to log this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1148)

2017-01-30 13:30 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            oos.writeObject(database);
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Make the "java.util.List" class "Serializable" or don't write it. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS2118)

2017-01-30 13:30 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +    {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Move the contents of this initializer to a standard constructor or to field initializers. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1171)

2017-01-30 13:30 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +        } catch (IOException ex) { //FIXME: Either log or rethrow this exception.
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Take the required action to fix the issue indicated by this comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1134)
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Either log or rethrow this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1166)

2017-01-30 13:30 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            ex.printStackTrace(); //FIXME: Use a logger to log this exception.
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Take the required action to fix the issue indicated by this comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1134)
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Use a logger to log this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1148)

2017-01-30 13:30 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +        } catch (IOException ex) { //FIXME: Either log or rethrow this exception.
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Take the required action to fix the issue indicated by this comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1134)
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Either log or rethrow this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1166)

2017-01-30 13:30 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            ex.printStackTrace(); //FIXME: Use a logger to log this exception.
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Take the required action to fix the issue indicated by this comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1134)
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Use a logger to log this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1148)

2017-01-30 13:30 UTC, Sheptytskyid commented
SonarQube analysis reported 14 issues
* ![MAJOR][MAJOR] 11 major
* ![MINOR][MINOR] 3 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-01-30 14:43 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/HotelDaoImpl.java
> +import com.manardenza.utils.DatabaseSeeder;
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Remove this unused import 'com.manardenza.utils.DatabaseSeeder'. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AUselessImportCheck)

2017-01-30 14:43 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/HotelDaoImpl.java
> +    {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Move the contents of this initializer to a standard constructor or to field initializers. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1171)

2017-01-30 14:43 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +        } catch (IOException | ClassNotFoundException ex) { //FIXME: Either log or rethrow this exception.
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Take the required action to fix the issue indicated by this comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1134)
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Either log or rethrow this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1166)

2017-01-30 14:43 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            ex.printStackTrace(); //FIXME: Use a logger to log this exception.
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Take the required action to fix the issue indicated by this comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1134)
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Use a logger to log this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1148)

2017-01-30 14:43 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +        } catch (IOException ex) { //FIXME: Either log or rethrow this exception.
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Take the required action to fix the issue indicated by this comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1134)
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Either log or rethrow this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1166)

2017-01-30 14:43 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            ex.printStackTrace(); //FIXME: Use a logger to log this exception.
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Take the required action to fix the issue indicated by this comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1134)
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Use a logger to log this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1148)

2017-01-30 14:43 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/UserDaoImpl.java
> +import java.util.List;
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Remove this unused import 'java.util.List'. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AUselessImportCheck)

2017-01-30 14:43 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/UserDaoImpl.java
> +    {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Move the contents of this initializer to a standard constructor or to field initializers. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1171)

2017-01-30 14:43 UTC, Sheptytskyid commented on src/main/java/com/manardenza/Main.java
> +import com.manardenza.utils.DatabaseSeeder;
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Remove this unused import 'com.manardenza.utils.DatabaseSeeder'. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AUselessImportCheck)

2017-01-30 14:43 UTC, Sheptytskyid commented
SonarQube analysis reported 18 issues
* ![MAJOR][MAJOR] 12 major
* ![MINOR][MINOR] 6 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-01-30 15:36 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            oos.writeObject(database);
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Make the "java.util.List" class "Serializable" or don't write it. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS2118)

2017-01-30 15:36 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +        } catch (IOException e) { //FIXME: Either log or rethrow this exception.
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Take the required action to fix the issue indicated by this comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1134)
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Either log or rethrow this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1166)

2017-01-30 15:36 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            e.printStackTrace();//FIXME: Use a logger to log this exception.
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Take the required action to fix the issue indicated by this comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1134)
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Use a logger to log this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1148)

2017-01-30 15:36 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +        } catch (IOException | ClassNotFoundException e) { //FIXME: Either log or rethrow this exception.
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Take the required action to fix the issue indicated by this comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1134)
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Either log or rethrow this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1166)

2017-01-30 15:36 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            e.printStackTrace();//FIXME: Use a logger to log this exception.
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Take the required action to fix the issue indicated by this comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1134)
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Use a logger to log this exception. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1148)

2017-01-30 15:36 UTC, Sheptytskyid commented
SonarQube analysis reported 9 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 2 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-01-30 17:21 UTC, zozich approved these changes
Cool!

2017-01-30 17:21 UTC, Sheptytskyid commented on src/main/java/com/manardenza/dao/AbstractDao.java
> +            oos.writeObject(database);
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Make the "java.util.List" class "Serializable" or don't write it. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS2118)

2017-01-30 17:21 UTC, merged