Travis.yml
Sheptytskyid/JavaCoreFinalProjectGroup6 pull request #5
Opened 2017-01-21 08:40 UTC by semyonov-m-y

Added .travis.yml, please check

2017-01-21 13:09 UTC, zozich commented on .travis.yml
> +  - oraclejdk7
Why do you want to test against jdk7?

2017-01-21 13:09 UTC, zozich commented on checkstyle_config.xml
> +      <property name="basicOffset" value="2"/>
We use indentation of 2 instead of 4 on our current project. If you wish, you may leave 4 here and on next 2 lines as well.

2017-01-22 15:11 UTC, Sheptytskyid commented on .travis.yml
> +language: java
Для інтеграції з Coveralls потрібно замінити:
language: java

jdk:
  - oraclejdk8

script:
  - mvn clean test jacoco:report coveralls:report

2017-01-22 16:18 UTC, Sheptytskyid approved these changes

2017-01-22 16:22 UTC, Sheptytskyid requested changes
потрібно забрати з цього pull request всі файли крім .travis.yml, а також коректно назвати файл ".travis.yml"

2017-01-22 18:22 UTC, Sheptytskyid submitted a review, later dismissed

2017-01-23 20:13 UTC, zozich approved these changes
OK

2017-01-23 20:13 UTC, merged